script to create vacancies and candidates tables
hh-interviewer-assistant/main pull request #14
Opened 2021-04-24 17:26 UTC by v-surg

сделал новую схему по минимуму с учетом того, о чем говорили на встрече (таблицы кандидатов и вакансий со статусами, статусы определены как enum)

2021-04-24 19:21 UTC, IvanIlin22 reviewed
вроде все основные поля есть

2021-04-24 19:21 UTC, IvanIlin22 commented on assistant/src/main/resources/create-tables.sql
> +);
Было бы неплохо добавить город и занятость

2021-04-24 19:21 UTC, IvanIlin22 commented on assistant/src/main/resources/create-tables.sql
> +);
добавить пустуя строку

2021-04-24 19:21 UTC, IvanIlin22 commented on assistant/src/main/resources/create-tables.sql
> +CREATE TYPE vac_status_type AS ENUM ('new', 'got-response', 'bla-bla-bla', 'offer-sent', 'closed');
bla-bla-bla может заменить на wait decision

2021-04-25 06:41 UTC, IvanIlin22 commented on assistant/src/main/resources/create-tables.sql
> +);
надо еще подумать как хранить резюме, либо путь к документу или еще как-то

2021-04-26 20:12 UTC, golovanovya commented on assistant/src/main/resources/create-tables.sql
> +        vac_status      vac_status_type,
Странный префикс, либо убрать, либо писать полностью vacancy

2021-04-26 20:12 UTC, golovanovya commented on assistant/src/main/resources/create-tables.sql
> +CREATE TABLE vacancies
В основном скрипте название таблиц в единственном числе, здесь же во множественном.

2021-04-26 20:13 UTC, golovanovya commented on assistant/src/main/resources/create-tables.sql
> +        phone   text[],
Поле хранит массив телефонов, а называется в единственном числе, в отличие от остальных полей, которые так же хранят массивы

2021-04-26 20:14 UTC, golovanovya commented on assistant/src/main/resources/create-tables.sql
> +        email   text not null,
Можно добавить составной индекс на уникальность имейла и id вакансии

2021-04-26 20:19 UTC, golovanovya commented on assistant/src/main/resources/create-tables.sql
> +        cand_status     cand_status_type,
Также странный префикс

2021-04-27 13:54 UTC, golovanovya commented on assistant/src/main/resources/create-tables.sql
> +        name    text not null,
Может для коротких полей использовать тип varchar, а не text?

2021-04-30 08:14 UTC, staanov requested changes
Смотри, я не сказал об этом всем (сорри), но есть ряд пожеланий по тому как оформлять SQL скрипты:
1) скрипты кладём в папку scripts/sql
2) одна задача - один скрипт
3) именуем скрипты по названию задачи, например, A-33.sql

Поправь это плиз, без этого не апрувну, иначе каша со скриптами будет.

2021-04-30 08:14 UTC, staanov commented on assistant/src/main/resources/create-tables.sql
> +CREATE TABLE vacancies
+1. К тому же в hh соглашение именовать таблицы в единственном числе, так что переименуй плиз

2021-04-30 08:14 UTC, staanov commented on assistant/src/main/resources/create-tables.sql
> +        name    text not null,
В целом согласен с Юрой, но вообще это не столь принципиально

2021-04-30 08:14 UTC, staanov commented on assistant/src/main/resources/create-tables.sql
> +);
А мы вообще как-то продумывали работу с городами? Насколько я помню, нет. Лучше сходите к продактам. Если у нас не будет множества городов в MVP (а будет, к примеру, только Москва), то можно не париться и не делать лишнее поле. А вот занятость думаю нужна.

2021-04-30 17:35 UTC, v-surg commented on assistant/src/main/resources/create-tables.sql
> +);
Ok, уберу город

2021-05-03 13:17 UTC, staanov approved these changes

2021-05-03 13:17 UTC, staanov commented on scripts/sql/A-33.sql
> +        gender  int,
Только сейчас глаз зацепился: лучше единообразия придерживаться, а то не понятно почему иногда int, а иногда integer.

2021-05-05 05:08 UTC, merged