A 28
hh-interviewer-assistant/main pull request #18
Opened 2021-05-12 05:11 UTC by IvanIlin22

1. GET http://localhost:8080/candidate/ - получение всех кандидатов
2. GET http://localhost:8080/candidate/{candidate_id} - получение кандидата по id
3. POST http://localhost:8080/candidate/add - добавить нового кандидата 
```json
{
    "first_name":"test4",
    "last_name":"Васильевна",
    "status":0,
    "age":18,
    "gender":0,
    "phones":["+79012349699"],
    "email":"Test4@email.com",
    "skills":[
        "ООП", 
        "C#",
        "C",
        "C++"
    ],
    "vacancy":{
        "vacancy_id":3   
    }
}
```
4. POST http://localhost:8080/candidate/update/ - обновление кандидата 
```json
{
    "candidate_id": 1,
    "first_name":"test4",
    "last_name":"Васильевна",
    "status":0,
    "age":18,
    "gender":0,
    "phones":["+79012349699"],
    "email":"Test4@email.com",
    "skills":[
        "ООП", 
        "C#",
        "C",
        "C++"
    ],
    "vacancy":{
        "vacancy_id":3   
    }
}
```
5. DELETE http://localhost:8080/candidate/{candidate_id}  - удаление кандидата

2021-05-12 06:25 UTC, golovanovya commented
У кандидата может быть несколько вакансий?
```
"vacancy":{
    "vacancy_id":3   
}
```
Может просто оставить
```
"vacancy_id": 3
```

`/candidate/update/status `
Обновляется только статус? Зачем тогда столько остальных полей?
Может тогда использовать PUT `/canidate/:id` или если нужно обновить только несколько полей, то PATCH

Может использовать вместо POST `/candidate/add` просто POST `/candidate`?

Можно поменять поле candidate_id на просто id?

2021-05-12 08:38 UTC, golovanovya commented
Может убрать поле статус при создании вакансии?

2021-05-15 12:47 UTC, golovanovya commented on assistant/src/main/java/ru/hh/school/entity/Candidate.java
> +	@Column(name = "first_name")
Не хватает переносов между полями из-за аннотаций они очень плохо читаются

2021-05-15 13:56 UTC, staanov requested changes

2021-05-15 13:56 UTC, staanov commented on assistant/src/main/java/ru/hh/school/dto/CandidateDto.java
> +	private String[] phones;
А почему ArrayList заюзать не хочешь? С ним обычно приятнее работать, чем с обычным массивом

2021-05-15 13:56 UTC, staanov commented on assistant/src/main/java/ru/hh/school/entity/Candidate.java
> +import javax.persistence.*;
В hh есть запрет на использование * в импортах (да, я могу забыть про что-то рассказать и какие-то знания вскрываются по ходу дела, сорян)

2021-05-15 13:56 UTC, staanov commented on assistant/src/main/java/ru/hh/school/entity/Candidate.java
> +)
Честно говоря, не сталкивался с такой аннотацией в Java, можешь пожалуйста рассказать зачем она вообще и зачем она нужна тут?

2021-05-15 13:56 UTC, staanov commented on assistant/src/main/java/ru/hh/school/entity/Vacancy.java
> +)
Тот же вопрос про аннотацию

2021-05-15 13:56 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/CandidateResource.java
> +	public CandidateResource(CandidateDao candidateDao, VacancyDao vacancyDao, CandidateMapper candidateMapper) {
Внедрить зависимости (@ Inject) не забыл?

2021-05-15 13:56 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/CandidateResource.java
> +import javax.ws.rs.*;
Тоже * в импортах

2021-05-15 13:56 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/VacancyResource.java
> +import javax.ws.rs.*;
Еще одна *

2021-05-15 13:56 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/VacancyResource.java
> +    public VacancyResource(VacancyDao vacDao, VacancyMapper vacancyMapper, CandidateMapper candidateMapper) {
И тоже не вижу, где ты инжектируешь dao, mapper и т.д.

2021-05-15 13:56 UTC, staanov commented on assistant/src/main/java/ru/hh/school/dto/VacancyDto.java
> +    @JsonSetter("id")
А точно здесь нужен Jackson? Недостаточно @ Produces(MediaType.APPLICATION_JSON) в ресурсе? Перепроверь это плиз, я могу ошибаться

2021-05-15 17:57 UTC, IvanIlin22 commented on assistant/src/main/java/ru/hh/school/entity/Candidate.java
> +)
Чтобы иметь возможность сопоставлять столбцы PostgreSQL ARRAY с атрибутами сущности Java List.

2021-05-15 18:12 UTC, IvanIlin22 commented on assistant/src/main/java/ru/hh/school/dto/VacancyDto.java
> +    @JsonSetter("id")
да здесь можно без Jackson, там просто раньше было vacancy_id, и вдруг надо будет поменять на какой другой поэтому аннотацию добавил ко всем полям

2021-05-15 18:41 UTC, golovanovya commented on assistant/src/main/java/ru/hh/school/dto/VacancyExpendDto.java
> +    @JsonSetter("candidate")
Лучше переименовать в candidates, т.к. возвращает множество кандидатов

2021-05-16 12:29 UTC, staanov reviewed
Поехавшее форматирование только поправь, остальное вроде ок

2021-05-16 12:29 UTC, staanov commented on assistant/src/main/java/ru/hh/school/config/ProdConfig.java
> +	}
Что-то ничего не поменялось:( твоя задача тут - добиться, чтобы это диффа вообще не было (в "старом" варианте всё ок с форматированием)

2021-05-16 12:59 UTC, IvanIlin22 commented on assistant/src/main/java/ru/hh/school/config/ProdConfig.java
> +	}
надеюсь правильно нашел тот "старый"

2021-05-16 13:29 UTC, staanov approved these changes

2021-05-16 13:52 UTC, merged