A-30
hh-interviewer-assistant/main pull request #19
Opened 2021-05-12 05:19 UTC by IvanIlin22

Реализовал изменение статуса вакансии по статусу кандидата. При изменении статуса кандидата находим максимальный статус кандидатов на эту вакансию и присваиваем ее вакансии.
1. POST http://localhost:8080/candidate/update/status - обновление кандидата 
```json
{
    "candidate_id": 1,
    "first_name":"test4",
    "last_name":"Васильевна",
    "status":5,
    "age":18,
    "gender":0,
    "phones":["+79012349699"],
    "email":"Test4@email.com",
    "skills":[
        "ООП", 
        "C#",
        "C",
        "C++"
    ],
    "vacancy":{
        "vacancy_id":3   
    }
}
```

2021-05-12 06:22 UTC, golovanovya commented
У кандидата может быть несколько вакансий?
```
"vacancy":{
    "vacancy_id":3   
}
```
Может просто оставить
```
"vacancy_id": 3
```

`/candidate/update/status `
Обновляется только статус? Зачем тогда столько остальных полей?
Может тогда использовать PUT `/canidate/:id` или если нужно обновить только несколько полей, то PATCH

2021-05-15 13:23 UTC, golovanovya commented on assistant/src/main/java/ru/hh/school/resource/CandidateResource.java
> +	@Path("/update/status")
Статус может обновится и в методе обновления кандидата, так же надо учитывать статус и при добавлении кандидата.

2021-05-16 18:19 UTC, staanov requested changes

2021-05-16 18:19 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/CandidateResource.java
> +	public CandidateResource(CandidateDao candidateDao, CandidateMapper candidateMapper,
Что-то я просмотрел этот момент в прошлом PR, сорян, но DAO в слое ресурсов не должно использоваться, как вариант убери в маппер и заюзай DAO там. Для примера можешь Топчик вспомнить https://github.com/hh-topchik/topchik/blob/master/topchik-service/src/main/java/ru/hh/topchik/resource/AppResource.java

2021-05-16 18:19 UTC, staanov commented on assistant/src/main/java/ru/hh/school/service/VacancyStatus.java
> +	public void changeStatus(CandidateDto candidateDto, CandidateDao candidateDao, VacancyDao vacancyDao) {
Соответственно, DAO лучше инжектировать, а не передавать аргументом

2021-05-17 05:25 UTC, IvanIlin22 commented on assistant/src/main/java/ru/hh/school/resource/CandidateResource.java
> +	public CandidateResource(CandidateDao candidateDao, CandidateMapper candidateMapper,
создал service слой, подумал слишком много функций появиться в mapper

2021-05-20 05:52 UTC, staanov commented on assistant/src/main/java/ru/hh/school/dao/CandidateDao.java
> +			.findFirst().get();
На мой взгляд тут без стрима можно обойтись, попробуй вместо getResultList() заюзать getSingleResult(), ну и в запросе можешь выставить что-то типа LIMIT 1, чтобы точно один результат был

2021-05-21 04:40 UTC, IvanIlin22 commented on assistant/src/main/java/ru/hh/school/dao/CandidateDao.java
> +			.findFirst().get();
забыл удалить

2021-05-21 09:19 UTC, staanov approved these changes

2021-05-22 05:20 UTC, merged