A 22 (+ A-21, A-24)
hh-interviewer-assistant/main pull request #21
Opened 2021-05-15 17:17 UTC by v-surg

добавил resource для импорта ваканисий с hh (ApihhResource):
- получение списка вакансий, размещенных на hh: /apihh/all
  возвращает json array вида [{'id': string, 'name': string}, ] при этом исключаются уже импортированные вакансии
- импорт по id: /store/{id}
  возвращает json {'result': string} ok или нет  

добавил поле hh_id  в сущность Vacancy и далее во все, что с ней связано

2021-05-16 12:11 UTC, IvanIlin22 reviewed
как я понимаю, мы смотрим на список всех вакансий Response getAll() и потом узнав их id  сохраняем у нас Response storeLocallyById. А нам нужна отдельно Response getAll() ? может лучше получать список всех вакансий и сразу их сохранять?

2021-05-16 12:11 UTC, IvanIlin22 commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +                        all.add(new VacancyHH(id, node.get("name").asText()));
Возможно я не прав, но мне кажется, что поход в APIHH можно в сервис слой засунуть, лучше посоветоваться со Стасом

2021-05-23 10:02 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +                        all.add(new VacancyHH(id, node.get("name").asText()));
Возможно

2021-05-23 10:02 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +    private final Map<String, Integer> emplymentMap= Map.ofEntries(
да, спасибо

2021-05-23 10:02 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +    private static final Logger logger = LoggerFactory.getLogger(RootResource.class);
ок

2021-05-23 10:02 UTC, v-surg commented
Насколько я помню, мы договаривались именно о таком функционале, смотрим какие у нас есть вакансии на hh и выбираем какую импортировать к себе.

2021-05-24 20:10 UTC, IvanIlin22 approved these changes

2021-05-24 20:10 UTC, IvanIlin22 commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +    }
ну и возможно стоит в отдельный класс

2021-05-28 17:02 UTC, v-surg commented on assistant/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
у меня иначе не компилируется

2021-05-28 17:04 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +    }
может, я не знаю какие правила. Мне показалось, что раз уж этот класс используется только здесь, то можно оставить это упрощенное решение.

2021-05-28 18:11 UTC, staanov requested changes

2021-05-28 18:11 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/VacancyResource.java
> +
лишний дифф

2021-05-28 18:11 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +import javax.ws.rs.*;
К сожалению, всем не сказал, только Ване в комментах к PR. Короче, в hh запрещены импорты через *, импортить надо каждый класс отдельно.

2021-05-28 18:11 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +import java.util.*;
Тоже импорт через *

2021-05-28 18:11 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +    }
Если этот класс нужен только здесь - оставляй здесь, только сделай его приватным

2021-05-28 18:11 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +                        all.add(new VacancyHH(id, node.get("name").asText()));
Согласен с Ваней, у нас есть сервис слой, поэтому перенеси плиз поход туда

2021-05-28 18:11 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +            Set<String> storedHhIDs = vacancyDao.getAllHhID();
Ниже отписал, но на всякий случай еще раз, у нас появился сервис слой, поэтому работай плиз с DAO не напрямую в ресурсах, а через сервис

2021-05-28 18:11 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +    public ApihhResource(VacancyDao vacancyDao) {
Ну про то, что работу с DAO надо убрать в сервис слой я написал, но если бы сервис слоя не было, то тут нужна была бы аннотация @ Inject перед конструктором

2021-05-29 15:52 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/dao/VacancyDao.java
> +    }
чтобы искать быстрее) вдруг у нас будет 10^6 вакансий)

2021-05-29 15:59 UTC, v-surg commented on assistant/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
Ok

2021-05-29 16:00 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +    }
Ok

2021-05-29 16:01 UTC, v-surg commented on assistant/pom.xml
> +</project>
Ok

2021-05-29 16:03 UTC, v-surg commented on assistant/src/etc/service.properties.dev
> +master.jdbcUrl=jdbc:postgresql://postgres:5432/postgres
я не исправлял, откуда-то выползло. у меня локально вообще другое подключение к базе в облаке.

2021-05-29 16:04 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/config/ProdConfig.java
> +	}
а как его вернуть?

2021-05-29 16:54 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +                        all.add(new VacancyHH(id, node.get("name").asText()));
Сделал сервис ApihhService

2021-05-29 16:54 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +    public ApihhResource(VacancyDao vacancyDao) {
Ok

2021-05-29 16:55 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/resource/ApihhResource.java
> +import java.util.*;
Исправил

2021-05-30 19:29 UTC, staanov requested changes

2021-06-02 18:42 UTC, staanov approved these changes

2021-06-04 19:01 UTC, merged