A 26 Vacancy card and candidates
hh-interviewer-assistant/main pull request #23
Opened 2021-05-16 21:49 UTC by golovanovya

2021-05-21 06:48 UTC, romanphilipskikh requested changes

2021-05-21 06:48 UTC, romanphilipskikh commented on static/src/components/CandidateCard.js
> +    return (
не обязательно, но чтобы candidate везде не писать можно написать так и использовать переменные дальше
```javascript
const { last_name, first_name , status, age, gender, skills } = candidate;
```

2021-05-21 06:48 UTC, romanphilipskikh commented on static/src/components/CandidateCard.js
> +    return (
и ты так ниже и делаешь в нескольких местах, а тут почему-то скипанул)

2021-05-21 06:48 UTC, romanphilipskikh commented on static/src/components/VacancyView.js
> +                        {vacancy.candidates &&
тут кажется `vacancy.candidates` лишнее, ты уже выше проверил же, что кандидаты есть 
и чуть ниже такое же

2021-05-21 06:48 UTC, romanphilipskikh commented on static/src/components/VacancyView.js
> +                                        </Button>
Компонент огромный получился сложно читать. Т.к. эти кнопки зависят от статуса и по большей части одинаковые давай вынесем их в отдельный компонент и будем статус передавать как проп и там уже разруливать её цвет и какой статус мы передаём в /candidates/update

И  обработчик onClick здоровенный тоже, его лучше вынести из верстки до return куда-нибудь.

2021-05-21 06:53 UTC, golovanovya commented on static/src/components/CandidateCard.js
> +    return (
В этом месте мне так удобнее просто обращаться)

2021-05-24 06:07 UTC, romanphilipskikh approved these changes

2021-05-24 10:24 UTC, merged