A 25 Vacancy columns
hh-interviewer-assistant/main pull request #24
Opened 2021-05-17 06:45 UTC by golovanovya

2021-05-24 18:07 UTC, romanphilipskikh requested changes

2021-05-24 18:07 UTC, romanphilipskikh commented on static/src/components/VacancyList.js
> +                </Grid>
давай колонки отдельно вынесем тоже?

2021-05-24 18:09 UTC, golovanovya commented on static/src/components/VacancyList.js
> +                </Grid>
Просто компонент это по сути колонки и есть

2021-05-25 07:57 UTC, romanphilipskikh approved these changes

2021-05-25 08:08 UTC, merged