A 40 - вакансии
hh-interviewer-assistant/main pull request #26
Opened 2021-05-26 09:57 UTC by YaSigara

2021-05-27 15:19 UTC, IvanIlin22 approved these changes
вроде все поправил, только у меня вопрос по тому что вставили

2021-05-27 15:19 UTC, IvanIlin22 commented on scripts/sql/A-40.sql
> +ADD COLUMN people integer;
добавь переход на новую строку в конце. вроде надо было добавить поля вопросов и ответов. что такое patterns и зачем people?

2021-05-29 10:09 UTC, YaSigara commented on scripts/sql/A-40.sql
> +ADD COLUMN people integer;
Patterns - шаблоны ответов, people - счетчик количества людей. Была отдельная карточка - я 2 объединил.

2021-05-29 18:45 UTC, golovanovya commented on scripts/sql/A-40.sql
> +ADD COLUMN people integer;
Тоже кажется неочевидным patterns. Думаю лучше тогда уж назвать пояснения или правильные ответы.

2021-05-30 09:10 UTC, staanov requested changes

2021-06-02 07:36 UTC, staanov approved these changes

2021-06-03 16:09 UTC, merged