A-39
hh-interviewer-assistant/main pull request #28
Opened 2021-05-29 14:43 UTC by IvanIlin22

- [x] При обновлении и добавлении в ответе отправляется сущность.

https://trello.com/c/2Hapx5Kt/48-back-a-39-%D0%BF%D1%80%D0%B8-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B8-%D0%B2-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%B5-%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D1%82%D1%8C-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D1%8C

2021-05-29 15:52 UTC, golovanovya commented
Может not found возвращать вместо bad request?

2021-06-05 12:15 UTC, golovanovya commented on assistant/src/main/java/ru/hh/school/service/CandidateService.java
> +			return null;
Null возвращать не очень хорошая практика, можно выкинуть исключение

2021-06-09 10:51 UTC, YaSigara approved these changes

2021-06-10 06:50 UTC, staanov requested changes
Еще есть косяк, который не могу отменить на ревью:
https://github.com/hh-interviewer-assistant/main/blob/A-39/assistant/src/main/java/ru/hh/school/resource/CandidateResource.java#L57
в Java используется camelCase, так что замени candidate_id на candidateId

2021-06-10 06:50 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/VacancyResource.java
> +        return Response.ok(vacancyService.updateVacancy(vacancyDto)).build();
Лучше вынеси `vacancyService.updateVacancy(vacancyDto)` в переменную, а ее уже в ok()

2021-06-10 06:50 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/CandidateResource.java
>  			: Response.ok(response).build();
Вообще, при проблемах с нахождением сущностей (а candidateExpendDto == null значит что dto по id'шнику не нашлось) мы обычно кидаем 404, пример из hh - https://spb.hh.ru/catalog/Sportivnye-kluby-fitnes-salony-ka, это попытка обратиться к каталогу с несуществующей профобластью. Если вы с Юрой договорились, что он принимает в таких случаях NOT_FOUND, ок, но рассмотрите вариант с 404.

2021-06-10 06:50 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/CandidateResource.java
> +		return Response.ok(candidateService.updateCandidate(candidateDto)).build();
аналогично - лучше в отдельную переменную

2021-06-11 07:09 UTC, staanov approved these changes

2021-06-11 13:33 UTC, merged