A-29
hh-interviewer-assistant/main pull request #29
Opened 2021-05-30 19:26 UTC by IvanIlin22

- [x] Реализовал добавление кандидата через pdf файл.

# Кандидат

1. POST http://localhost:8080/candidates/upload/{vacancy_id} - добавление кандидата 
Файл отправляем в body, form-data, file

2021-06-05 12:31 UTC, golovanovya commented on assistant/src/main/java/ru/hh/school/parser/ParserPDF.java
> +	public void writeToFile(InputStream uploadedInputStream,
Может отдельный класс добавить для сохранения резюме, которые просто прикрепляются к кандидатам и не предназначены для парсинга.

2021-06-08 18:58 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/parser/ParserPDF.java
> +		var skills = skillsText.substring(0, skillsText.indexOf("\n")).split("      ");
Здесь точно не нужны проверки на валидность индексов в массиве? Может стоит все это обернуть в try/catch, на случай отличия формата PDF от предполагаемого?

2021-06-08 18:58 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/service/CandidateService.java
> +		String uploadedFileLocation = "src/main/storage/test.pdf";
называя все файлы одинаково (до переименования) не создаст проблем в многопоточной среде?

2021-06-08 18:58 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/service/CandidateService.java
> +			ex.printStackTrace();
ошибки, видимо, лучше логировать.

2021-06-08 18:58 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/service/CandidateService.java
> +			candidateDao.saveCandidate(candidate);
Здесь получается, что мы перекладываем данные туда-сюда, просто переписывая поля. Может проще возвращать Candidate из parserPDF?

2021-06-08 19:01 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/parser/ParserPDF.java
> +		var Info = mas[1].split(",");
мне кажется, лучше обозначать типы полностью, иначе страдает понятность кода

2021-06-09 21:30 UTC, IvanIlin22 commented on assistant/src/main/java/ru/hh/school/parser/ParserPDF.java
> +		var skills = skillsText.substring(0, skillsText.indexOf("\n")).split("      ");
Нас строго данный формат пока интересует, просто try catch все равно не спасет, даже если мы обернем данные могут не валидные попасть

2021-06-09 22:01 UTC, IvanIlin22 commented on assistant/src/main/java/ru/hh/school/service/CandidateService.java
> +		String uploadedFileLocation = "src/main/storage/test.pdf";
думаю это не получится сделать, я вынес сохранение резюме отдельным методом

2021-06-11 14:48 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/service/CandidateService.java
> +		return candidateMapper.mapExpend(candidate);
Зачем здесь возвращать CandidateDTO, если дальше только сравниваем его с null? может лучше вернуть boolean или int?

2021-06-11 14:48 UTC, v-surg commented on assistant/src/main/java/ru/hh/school/resource/CandidateResource.java
> +		}
может разумнее возвращать из uploadNewCandidate boolean или int, раз уж мы просто сравниваем с null?

2021-06-13 10:44 UTC, IvanIlin22 commented on assistant/src/main/java/ru/hh/school/service/CandidateService.java
> +		return candidateMapper.mapExpend(candidate);
мы возвращаем CandidateDTO, т.к при обнавлении выводим json CandidateDTO не только сравниваем с null

2021-06-13 10:48 UTC, IvanIlin22 commented on assistant/src/main/java/ru/hh/school/resource/CandidateResource.java
> +		}
мы не только сравниваем, но и вовращаем сущность CandidateDTO(на 98 строке), если ее не было до этого, null в том случае, если сущность уже существует и тогда не сохраняем, чтобы не дублировать записи.

2021-06-13 11:32 UTC, v-surg approved these changes

2021-06-13 19:02 UTC, staanov requested changes

2021-06-13 19:02 UTC, staanov commented on assistant/src/main/java/ru/hh/school/service/CandidateService.java
> +			return null;
Во-первых, так себе идея в catch блоке что-то возвращать. Во-вторых, предлагаю малость отрефакторить: `Candidate candidate = null` до try-catch, if вместе с сохранением сущности из try можешь вынести за try-catch и добавить проверку на `candidate != null` (`if candidate == null { return null; }`). тогда return'а в try-catch вообще не будет (если я вдруг накосячил и это не сработает, то в try оставлять return еще норм, но из catch его надо убирать)

2021-06-13 19:02 UTC, staanov commented on assistant/src/main/java/ru/hh/school/service/CandidateService.java
> +		Candidate candidate = candidateDao.getCandidateById(candidate_id);
candidate_id не в camelCase

2021-06-13 20:08 UTC, staanov commented on assistant/src/main/java/ru/hh/school/parser/ParserPDF.java
> +		if (Info[0].equals("Мужчина")) {
А если `Info[0] = "мужчина"`? Или такого быть не может? В любом случае более генерно будет Info[0] привести, например, к lower case и сравнивать с "мужчина"

2021-06-13 20:08 UTC, staanov commented on assistant/src/main/java/ru/hh/school/resource/CandidateResource.java
> +			return Response.serverError().build();
Для пущей красоты можешь еще залоггировать:)

2021-06-14 06:45 UTC, staanov approved these changes

2021-06-14 07:00 UTC, merged