A 12 vacancy form
hh-interviewer-assistant/main pull request #5
Opened 2021-04-05 05:50 UTC by golovanovya

2021-04-12 09:07 UTC, romanphilipskikh commented on static/src/index.js
> +// import "normalize.css";
удали коммент

2021-04-12 11:23 UTC, romanphilipskikh commented on static/src/components/VacancyForm.js
> +const marks = [
Можно оставить, но в будущем все константы капсом. Типа 
`VACANCY_RECOMMENDATIONS = {} `

2021-04-12 11:40 UTC, romanphilipskikh commented on static/src/components/VacancyForm.js
> +export default function VacancyFrom(props) {
просто совет - удобнее использовать деструктуризацию https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

```suggestion
export default function VacancyFrom({ vacancy, position }) {
```

2021-04-12 11:49 UTC, romanphilipskikh commented on static/src/components/InputItemsList.js
> +            {0 <
```suggestion
            {props.recommendations.filter(
                    (recommendation) => !items.includes(recommendation)
                ).length > 0
```

2021-04-12 11:50 UTC, romanphilipskikh commented on static/src/components/InputItemsList.js
> +                <div style={{ margin: "10px auto" }}>
лучше инлайново стили не писать, а навесить класс здесь

2021-04-12 11:53 UTC, romanphilipskikh requested changes
Слушай, ну для данного этапа нормально, мне всё нравится в целом. 
Буквально пару минорных комментов поправить и ок. НО! Обязательно нужно показать продактам, возможно у них будут вопросы по верстке и чему-то ещё. Наверное сегодня на созвоне. 

+ ещё у меня плэйсхолдер едет чуток
<img width="724" alt="Снимок экрана 2021-04-12 в 14 30 57" src="https://user-images.githubusercontent.com/41548650/114390385-dd028500-9b9e-11eb-8b4f-1c75b6c6f946.png">

2021-04-12 12:18 UTC, golovanovya commented on static/src/components/InputItemsList.js
> +            {0 <
Почему такой вариант лучше?

2021-04-13 06:45 UTC, romanphilipskikh approved these changes

2021-04-13 06:50 UTC, merged